"""Add created_at field to users table

Revision ID: f595ad0c2895
Revises: d7dfa832cc4e
Create Date: 2025-11-01 09:10:55.070786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f595ad0c2895'
down_revision = 'd7dfa832cc4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # Update existing records with current timestamp
    op.execute("UPDATE users SET created_at = datetime('now') WHERE created_at IS NULL")
    
    # Alter the column to be NOT NULL
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
